"""
views.py — Cozy Triage view layer.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from core.forms import SignupForm
from core.services import graphrag_service
from core.dtos import UserNode, TaskStatus

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Auth views
# ---------------------------------------------------------------------------

def signup(request):
    """
    Create a Django user + matching Memgraph User node.
    On success, log the user in and redirect to dashboard.
    """
    if request.user.is_authenticated:
        return redirect("dashboard")

    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            django_user = form.save()
            # Sync to Memgraph — use Django's pk as the graph node id
            node = UserNode(
                id=str(django_user.pk),
                email=django_user.email,
                created_at=datetime.now(timezone.utc),
            )
            try:
                graphrag_service.create_user(node)
            except Exception:
                logger.exception(
                    "Memgraph User node creation failed for pk=%s", django_user.pk
                )
                # Don't block login — node sync can be retried; user exists in Django
            login(request, django_user)
            return redirect("dashboard")
    else:
        form = SignupForm()

    return render(request, "core/signup.html", {"form": form})


# ---------------------------------------------------------------------------
# Dashboard
# ---------------------------------------------------------------------------

@login_required
def dashboard(request):
    """
    Home view — shows top Next Actions and a quick-add input.
    """
    user_id = str(request.user.pk)
    next_tasks = []
    inbox_count = 0

    try:
        next_tasks = graphrag_service.list_tasks(user_id, status=TaskStatus.NEXT)[:5]
        inbox_tasks = graphrag_service.list_tasks(user_id, status=TaskStatus.INBOX)
        inbox_count = len(inbox_tasks)
    except Exception:
        logger.exception("Failed to load dashboard tasks for user %s", user_id)

    return render(request, "core/dashboard.html", {
        "next_tasks": next_tasks,
        "inbox_count": inbox_count,
    })


# ---------------------------------------------------------------------------
# Triage Pipeline
# ---------------------------------------------------------------------------

@login_required
def inbox(request):
    """
    Brain dump input form. On POST, runs the brain dump through the triage pipeline.
    """
    user_id = str(request.user.pk)
    
    if request.method == "POST":
        brain_dump = request.POST.get("brain_dump", "").strip()
        if not brain_dump:
            return render(request, "core/inbox.html", {
                "error": "Please enter what's on your mind.",
            })
            
        from core.services import triage_service
        result = triage_service.run_triage(user_id, brain_dump)
        
        if result.get("error"):
            # If the LLM call or graph call completely failed
            return render(request, "core/inbox.html", {
                "error": result["error"],
                "brain_dump_content": brain_dump,
            })
            
        session_id = result["session_id"]
        return redirect("triage_review", session_id=session_id)
        
    return render(request, "core/inbox.html")


@login_required
def triage_review(request, session_id):
    """
    Review suggestions generated by the triage pipeline.
    """
    user_id = str(request.user.pk)
    
    # Check if session exists and is owned by user
    session = graphrag_service.get_triage_session(user_id, session_id)
    if not session:
        return redirect("inbox")
        
    if request.method == "POST":
        from core.services import triage_service
        import json
        try:
            # Expected payload: '[{"id": "sug_uuid", "action": "accept", "edited_data": {...}}]'
            decisions = json.loads(request.POST.get("decisions", "[]"))
            triage_service.apply_suggestions(user_id, session_id, decisions)
            return redirect("tasks")
        except Exception as e:
            logger.exception(f"Failed to apply suggestions for session {session_id}")
            # Fall through to GET below and show error
            pass
            
    # GET: fetch suggestions
    suggestions = graphrag_service.get_suggestions_for_session(user_id, session_id)
    
    # Filter out already accepted/rejected suggestions
    pending_suggestions = [s for s in suggestions if s.accepted_bool is None]
    
    # If no pending suggestions left, this session is done
    if not pending_suggestions and suggestions:
        return redirect("tasks")
       
    # Parse payload back into Python dicts for the template
    import json
    parsed_suggestions = []
    for s in pending_suggestions:
        try:
            payload = json.loads(s.payload_json)
            parsed_suggestions.append({
                "id": s.id,
                **payload
            })
        except:
            pass
            
    return render(request, "core/triage_review.html", {
        "session": session,
        "suggestions": parsed_suggestions,
    })


# ---------------------------------------------------------------------------
# Tasks
# ---------------------------------------------------------------------------

@login_required
def tasks(request):
    """
    Stub for Phase 5 tasks view.
    """
    return render(request, "core/base.html", {"message": "Tasks placeholder (Phase 5)"})
